name: PSITS-WEBSITE | CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Open Office Management Directory
        working-directory: frontend/psits_frontend
        run: |
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: frontend/psits_frontend
        run: npm install

      # - name: Run Code Linting
      #   working-directory: frontend/psits_frontend
      #   run: npm run lint

      - name: Build Code
        working-directory: frontend/psits_frontend
        run: npm run build
