name: OfficeManagement

on:
  push:
    branches:
      - master
    paths:
      - "frontend/psits_frontend_officemanagement/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
        paths:
          - "frontend/psits_frontend_officemanagement/**"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        paths:
          - "frontend/psits_frontend_officemanagement/**"

      - name: Build project
        run: npm run build
        env:
          VITE_SERVER_URL_API: ${{ secrets.VITE_SERVER_URL_API }}
          VITE_SERVER_API_KEY: ${{ secrets.VITE_SERVER_API_KEY }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist
